import { describe, expect, it } from 'vitest';
import { adaptBody } from '../src/body';

describe('adaptBody six-type matrix', () => {
  it('undefined → no body, no Content-Type', () => {
    const r = adaptBody(undefined);
    expect(r.body).toBeUndefined();
    expect(r.contentType).toBeUndefined();
  });

  it('plain object → JSON string + application/json', () => {
    const r = adaptBody({ x: 1, y: 'a' });
    expect(r.body).toBe(JSON.stringify({ x: 1, y: 'a' }));
    expect(r.contentType).toBe('application/json');
  });

  it('array → JSON string + application/json', () => {
    const r = adaptBody([1, 2, 3]);
    expect(r.body).toBe('[1,2,3]');
    expect(r.contentType).toBe('application/json');
  });

  it('null → "null" + application/json', () => {
    const r = adaptBody(null);
    expect(r.body).toBe('null');
    expect(r.contentType).toBe('application/json');
  });

  it('string → JSON serialization (quoted) + application/json', () => {
    const r = adaptBody('hello');
    expect(r.body).toBe('"hello"');
    expect(r.contentType).toBe('application/json');
  });

  it('number/boolean → JSON serialization + application/json', () => {
    expect(adaptBody(42)).toEqual({ body: '42', contentType: 'application/json' });
    expect(adaptBody(true)).toEqual({ body: 'true', contentType: 'application/json' });
  });

  it('Blob with a type → passed through as-is with that type', () => {
    const blob = new Blob([new Uint8Array([1, 2])], { type: 'image/png' });
    const r = adaptBody(blob);
    expect(r.body).toBe(blob);
    expect(r.contentType).toBe('image/png');
  });

  it('Blob without a type (same for a File with an empty type) → passed through as-is + application/octet-stream', () => {
    const blob = new Blob([new Uint8Array([1])]);
    const r = adaptBody(blob);
    expect(r.body).toBe(blob);
    expect(r.contentType).toBe('application/octet-stream');
  });

  it('FormData → passed through as-is without Content-Type (the boundary is generated by fetch)', () => {
    const fd = new FormData();
    fd.set('k', 'v');
    const r = adaptBody(fd);
    expect(r.body).toBe(fd);
    expect(r.contentType).toBeUndefined();
  });

  it('ReadableStream → passed through as-is + application/octet-stream', () => {
    const rs = new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(new Uint8Array([1]));
        controller.close();
      },
    });
    const r = adaptBody(rs);
    expect(r.body).toBe(rs);
    expect(r.contentType).toBe('application/octet-stream');
  });

  it('Uint8Array → passed through as-is + application/octet-stream', () => {
    const bytes = new Uint8Array([9, 9]);
    const r = adaptBody(bytes);
    expect(r.body).toBe(bytes);
    expect(r.contentType).toBe('application/octet-stream');
  });

  it('ArrayBuffer → passed through as-is + application/octet-stream', () => {
    const buf = new ArrayBuffer(4);
    const r = adaptBody(buf);
    expect(r.body).toBe(buf);
    expect(r.contentType).toBe('application/octet-stream');
  });
});
