import { describe, expect, it, vi } from 'vitest';
import { createClient } from '../src/client';
import { ApiError } from '../src/errors';

type FetchSpy = ReturnType<typeof vi.fn>;

function makeClient(fetchImpl: unknown) {
  return createClient(
    { baseUrl: 'http://127.0.0.1:39876/api', token: 'test-token' },
    { fetchImpl: fetchImpl as typeof fetch },
  );
}

function jsonResponder(status = 200, body: unknown = { ok: true }) {
  return async (_input: RequestInfo | URL, _init?: RequestInit) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { 'content-type': 'application/json' },
    });
}

describe('createClient', () => {
  it('get: URL join + Authorization header, GET carries no Content-Type', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    await client.get('/todo/list');
    const [input, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(input).toBe('http://127.0.0.1:39876/api/todo/list');
    expect(init.method).toBe('GET');
    expect((init.headers as Record<string, string>)['Authorization']).toBe('Bearer test-token');
    expect((init.headers as Record<string, string>)['Content-Type']).toBeUndefined();
  });

  it('post object: Content-Type application/json + JSON-serialized bytes', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    await client.post('/todo/items', { title: '买牛奶', done: false });
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(init.method).toBe('POST');
    expect(init.body).toBe(JSON.stringify({ title: '买牛奶', done: false }));
    expect((init.headers as Record<string, string>)['Content-Type']).toBe('application/json');
  });

  it('post Blob: Content-Type taken from blob.type, body passed through as-is', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    const blob = new Blob([new Uint8Array([1])], { type: 'application/pdf' });
    await client.post('/upload', blob);
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(init.body).toBe(blob);
    expect((init.headers as Record<string, string>)['Content-Type']).toBe('application/pdf');
  });

  it('post FormData: no Content-Type (the boundary is generated by fetch), custom user headers allowed', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    const fd = new FormData();
    fd.set('file', new Blob(['x']), 'a.txt');
    await client.post('/upload', fd, { headers: { 'X-Trace': 't1' } });
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(init.body).toBe(fd);
    expect((init.headers as Record<string, string>)['Content-Type']).toBeUndefined();
    expect((init.headers as Record<string, string>)['X-Trace']).toBe('t1');
    expect((init.headers as Record<string, string>)['Authorization']).toBe('Bearer test-token');
  });

  it('head/delete/put pass the method name through correctly', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    await client.head('/ping');
    await client.delete('/todo/items/1');
    await client.put('/todo/items/1', { done: true });
    const methods = spy.mock.calls.map((c) => (c[1] as RequestInit).method);
    expect(methods).toEqual(['HEAD', 'DELETE', 'PUT']);
  });

  it('query params serialized into the URL (numbers and booleans included)', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    await client.get('/todo/list', { query: { status: 'open', limit: 20, pinned: true } });
    const [input] = spy.mock.calls[0] as [string, RequestInit];
    expect(input).toBe(
      'http://127.0.0.1:39876/api/todo/list?status=open&limit=20&pinned=true',
    );
  });

  it('non-2xx JSON body → throws ApiError (status + parsed object body)', async () => {
    const spy = vi.fn(jsonResponder(422, { message: 'title must not be empty' })) as FetchSpy;
    const client = makeClient(spy);
    const err = await client.post('/todo/items', {}).catch((e) => e);
    expect(err).toBeInstanceOf(ApiError);
    expect(err.status).toBe(422);
    expect(err.body).toEqual({ message: 'title must not be empty' });
    expect(err.raw).toBeInstanceOf(Response);
  });

  it("non-2xx text body → ApiError.message in the 'API 404: <body>' form", async () => {
    const spy = vi.fn(async () => new Response('not found', { status: 404 })) as FetchSpy;
    const client = makeClient(spy);
    const err = await client.get('/nope').catch((e) => e);
    expect(err).toBeInstanceOf(ApiError);
    expect(err.message).toBe('API 404: not found');
    expect(err.body).toBe('not found');
  });

  it('network error (fetch rejects) propagates as-is, not an ApiError', async () => {
    const boom = new TypeError('fetch failed');
    const spy = vi.fn(async () => {
      throw boom;
    }) as FetchSpy;
    const client = makeClient(spy);
    const err = await client.get('/x').catch((e) => e);
    expect(err).toBe(boom);
    expect(err).not.toBeInstanceOf(ApiError);
  });

  it('signal passed through to the fetch init', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    const ctrl = new AbortController();
    await client.get('/slow', { signal: ctrl.signal });
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(init.signal).toBe(ctrl.signal);
  });

  it('user headers can override the automatic Authorization', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    await client.get('/x', { headers: { Authorization: 'Bearer custom' } });
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect((init.headers as Record<string, string>)['Authorization']).toBe('Bearer custom');
  });

  it('path not starting with / → throws a TypeError synchronously', () => {
    const client = makeClient(vi.fn(jsonResponder()));
    expect(() => client.get('todo/list')).toThrow(TypeError);
    expect(() => client.post('x', {})).toThrow(TypeError);
    expect(() => client.request('PUT', 'y')).toThrow(TypeError);
  });

  it('baseUrl trailing-slash normalization: joins never produce a double slash (shape left undefined by the gateway)', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = createClient(
      { baseUrl: 'http://127.0.0.1:39876/api/', token: 'test-token' },
      { fetchImpl: spy as unknown as typeof fetch },
    );
    await client.get('/todo/list');
    const [input] = spy.mock.calls[0] as [string, RequestInit];
    expect(input).toBe('http://127.0.0.1:39876/api/todo/list');
  });

  it('post ReadableStream body: init injects duplex half (mandatory for fetch streaming bodies)', async () => {
    const spy = vi.fn(jsonResponder()) as FetchSpy;
    const client = makeClient(spy);
    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(new TextEncoder().encode('chunk'));
        controller.close();
      },
    });
    await client.post('/upload', stream);
    const [, init] = spy.mock.calls[0] as [string, RequestInit];
    expect(init.body).toBe(stream);
    expect((init as { duplex?: string }).duplex).toBe('half');
  });

  it('successful response wrapped as SdkResponse with a json() convenience', async () => {
    const spy = vi.fn(jsonResponder(200, { hello: 'world' })) as FetchSpy;
    const client = makeClient(spy);
    const res = await client.get('/x');
    expect(res.status).toBe(200);
    await expect(res.json<{ hello: string }>()).resolves.toEqual({ hello: 'world' });
  });
});
